version: '3'
services:
  homeassistant:
    container_name: homeassistant
    build: .
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
      - 51827:51827
    restart: unless-stopped
    privileged: true